"""empty message

Revision ID: 443ccbf3152f
Revises: 5a4fcf37cf80
Create Date: 2017-06-08 10:21:57.890437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '443ccbf3152f'
down_revision = '5a4fcf37cf80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergames', sa.Column('game_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'usergames_ibfk_1', 'usergames', type_='foreignkey')
    op.create_foreign_key(None, 'usergames', 'games', ['game_id'], ['id'])
    op.drop_column('usergames', 'game_isr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergames', sa.Column('game_isr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usergames', type_='foreignkey')
    op.create_foreign_key(u'usergames_ibfk_1', 'usergames', 'games', ['game_isr'], ['id'])
    op.drop_column('usergames', 'game_id')
    # ### end Alembic commands ###
