"""empty message

Revision ID: 855ead40144e
Revises: d6d4f51ecef0
Create Date: 2017-06-21 16:36:16.912877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855ead40144e'
down_revision = 'd6d4f51ecef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersocialids',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.Integer(), nullable=False),
    sa.Column('user_social_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['social_id'], ['socials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'social_id')
    )
    op.drop_table('usersocials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersocials',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('social_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['social_id'], [u'socials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], )
    )
    op.drop_table('usersocialids')
    # ### end Alembic commands ###
