"""empty message

Revision ID: d6d4f51ecef0
Revises: 53bda65896fa
Create Date: 2017-06-21 16:02:00.285559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d4f51ecef0'
down_revision = '53bda65896fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersocials',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('social_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['social_id'], ['socials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersocials')
    op.drop_table('socials')
    # ### end Alembic commands ###
